/********************************************************************************
** Form generated from reading UI file 'CharacterSheet.ui'
**
** Created by: Qt User Interface Compiler version 5.15.16
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CHARACTERSHEET_H
#define UI_CHARACTERSHEET_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CharacterSheet
{
public:
    QVBoxLayout *verticalLayout;
    QStackedWidget *stackedWidget;
    QWidget *page1;
    QGridLayout *gridLayout;
    QScrollArea *scrollArea1;
    QWidget *scrollAreaWidgetContents1;
    QGridLayout *gridLayout_4;
    QWidget *backGround1;
    QLineEdit *charNameLine;
    QLineEdit *charClassLevelLine;
    QLineEdit *charBackGroundLine;
    QLineEdit *charRaceLine;
    QLineEdit *charAlignmentLine;
    QLineEdit *expPointsLine;
    QSpinBox *strengthSpinBox;
    QSpinBox *dexteritySpinBox;
    QSpinBox *constitutionSpinBox;
    QSpinBox *intelligenceSpinBox;
    QSpinBox *wisdomSpinBox;
    QSpinBox *charismaSpinBox;
    QLineEdit *strengthLineEdit;
    QLineEdit *dexterityLineEdit;
    QLineEdit *constitutionLineEdit;
    QLineEdit *intelligenceLineEdit;
    QLineEdit *wisdomLineEdit;
    QLineEdit *charismaLineEdit;
    QLineEdit *passiveWisdomLineEdit;
    QLineEdit *playerNameLine;
    QPlainTextEdit *attackAndSpellEdit;
    QPlainTextEdit *profLangEdit;
    QPlainTextEdit *equipmentEdit;
    QPlainTextEdit *personalityTraitsEdit;
    QPlainTextEdit *idealsEdit;
    QPlainTextEdit *bondsEdit;
    QPlainTextEdit *flawsEdit;
    QPlainTextEdit *featuresTraitsEdit;
    QSpinBox *armorClassSpinBox;
    QSpinBox *initiativeSpinBox;
    QSpinBox *speedSpinBox;
    QSpinBox *hitPointsCurrentSpinBox;
    QSpinBox *hitPointsTemporarySpinBox;
    QSpinBox *hitDiceSpinBox;
    QSpinBox *coinsCopperSpinBox;
    QSpinBox *coinsSilverSpinBox;
    QSpinBox *coinsElectrumSpinBox;
    QSpinBox *coinsGoldSpinBox;
    QSpinBox *coinsPlatinumSpinBox;
    QSpinBox *savingThrowStrengthSpinBox;
    QSpinBox *savingThrowDexteritySpinBox;
    QSpinBox *savingThrowConstitutionSpinBox;
    QSpinBox *savingThrowIntelligenceSpinBox;
    QSpinBox *savingThrowWisdomSpinBox;
    QSpinBox *savingThrowCharismaSpinBox;
    QSpinBox *skillAcrobaticsSpinBox;
    QSpinBox *skillAnimalHandlingSpinBox;
    QSpinBox *skillArcanaSpinBox;
    QSpinBox *skillAthleticsSpinBox;
    QSpinBox *skillDeceptionSpinBox;
    QSpinBox *skillHistorySpinBox;
    QSpinBox *skillInsightSpinBox;
    QSpinBox *skillIntimidationSpinBox;
    QSpinBox *skillInvestigationSpinBox;
    QSpinBox *skillMedicineSpinBox;
    QSpinBox *skillNatureSpinBox;
    QSpinBox *skillPerceptionSpinBox;
    QSpinBox *skillPerformanceSpinBox;
    QSpinBox *skillPersuasionSpinBox;
    QSpinBox *skillReligionSpinBox;
    QSpinBox *skillSleightOfHandSpinBox;
    QSpinBox *skillStealthSpinBox;
    QSpinBox *skillSurvivalSpinBox;
    QLineEdit *inspirationLineEdit;
    QSpinBox *profBonusSpinBox;
    QLineEdit *hitPointsMaxLineEdit;
    QLineEdit *hitDiceTotalLineEdit;
    QLineEdit *attack1NameLineEdit;
    QLineEdit *attack2NameLineEdit;
    QLineEdit *attack3NameLineEdit;
    QLineEdit *attack1DamageTypeLineEdit;
    QLineEdit *attack2DamageTypeLineEdit;
    QLineEdit *attack3DamageTypeLineEdit;
    QSpinBox *attack1BonusSpinBox;
    QSpinBox *attack2BonusSpinBox;
    QSpinBox *attack3BonusSpinBox;
    QRadioButton *savingThrowStrengthRadioButton;
    QRadioButton *savingThrowDexterityRadioButton;
    QRadioButton *savingThrowConstitutionRadioButton;
    QRadioButton *savingThrowIntelligenceRadioButton;
    QRadioButton *savingThrowWisdomRadioButton;
    QRadioButton *savingThrowCharismaRadioButton;
    QRadioButton *skillAcrobaticsRadioButton;
    QRadioButton *skillAnimalHandlingRadioButton;
    QRadioButton *skillArcanaRadioButton;
    QRadioButton *skillAthleticsRadioButton;
    QRadioButton *skillDeceptionRadioButton;
    QRadioButton *skillHistoryRadioButton;
    QRadioButton *skillInsightRadioButton;
    QRadioButton *skillIntimidationRadioButton;
    QRadioButton *skillInvestigationRadioButton;
    QRadioButton *skillMedicineRadioButton;
    QRadioButton *skillNatureRadioButton;
    QRadioButton *skillPerceptionRadioButton;
    QRadioButton *skillPerformanceRadioButton;
    QRadioButton *skillPersuasionRadioButton;
    QRadioButton *skillReligionRadioButton;
    QRadioButton *skillSleightOfHandRadioButton;
    QRadioButton *skillStealthRadioButton;
    QRadioButton *skillSurvivalRadioButton;
    QRadioButton *success1RadioButton;
    QRadioButton *success2RadioButton;
    QRadioButton *success3RadioButton;
    QRadioButton *failur1RadioButton;
    QRadioButton *failur2RadioButton;
    QRadioButton *failur3RadioButton;
    QWidget *page2;
    QGridLayout *gridLayout_2;
    QScrollArea *scrollArea2;
    QWidget *scrollAreaWidgetContents2;
    QGridLayout *gridLayout_5;
    QWidget *backGround2;
    QWidget *page3;
    QGridLayout *gridLayout_3;
    QScrollArea *scrollArea3;
    QWidget *scrollAreaWidgetContents3;
    QGridLayout *gridLayout_6;
    QWidget *backGround3;
    QHBoxLayout *horizontalLayout;
    QSpacerItem *horizontalSpacer;
    QPushButton *buttonPrevPage;
    QPushButton *buttonNextPage;
    QSpacerItem *horizontalSpacer_2;

    void setupUi(QWidget *CharacterSheet)
    {
        if (CharacterSheet->objectName().isEmpty())
            CharacterSheet->setObjectName(QString::fromUtf8("CharacterSheet"));
        CharacterSheet->resize(989, 546);
        verticalLayout = new QVBoxLayout(CharacterSheet);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        stackedWidget = new QStackedWidget(CharacterSheet);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        page1 = new QWidget();
        page1->setObjectName(QString::fromUtf8("page1"));
        gridLayout = new QGridLayout(page1);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        scrollArea1 = new QScrollArea(page1);
        scrollArea1->setObjectName(QString::fromUtf8("scrollArea1"));
        scrollArea1->setWidgetResizable(false);
        scrollArea1->setAlignment(Qt::AlignCenter);
        scrollAreaWidgetContents1 = new QWidget();
        scrollAreaWidgetContents1->setObjectName(QString::fromUtf8("scrollAreaWidgetContents1"));
        scrollAreaWidgetContents1->setGeometry(QRect(-356, 0, 1293, 1668));
        gridLayout_4 = new QGridLayout(scrollAreaWidgetContents1);
        gridLayout_4->setObjectName(QString::fromUtf8("gridLayout_4"));
        backGround1 = new QWidget(scrollAreaWidgetContents1);
        backGround1->setObjectName(QString::fromUtf8("backGround1"));
        backGround1->setMinimumSize(QSize(1275, 1650));
        backGround1->setMaximumSize(QSize(1275, 1650));
        backGround1->setStyleSheet(QString::fromUtf8("background-image: url(:/dndcs/1.png);"));
        charNameLine = new QLineEdit(backGround1);
        charNameLine->setObjectName(QString::fromUtf8("charNameLine"));
        charNameLine->setGeometry(QRect(100, 130, 421, 41));
        QFont font;
        font.setFamily(QString::fromUtf8("URW Bookman L"));
        font.setPointSize(20);
        charNameLine->setFont(font);
        charNameLine->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        charNameLine->setFrame(false);
        charClassLevelLine = new QLineEdit(backGround1);
        charClassLevelLine->setObjectName(QString::fromUtf8("charClassLevelLine"));
        charClassLevelLine->setGeometry(QRect(560, 100, 231, 27));
        QFont font1;
        font1.setFamily(QString::fromUtf8("URW Bookman L"));
        font1.setPointSize(15);
        charClassLevelLine->setFont(font1);
        charClassLevelLine->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        charClassLevelLine->setFrame(false);
        charBackGroundLine = new QLineEdit(backGround1);
        charBackGroundLine->setObjectName(QString::fromUtf8("charBackGroundLine"));
        charBackGroundLine->setGeometry(QRect(800, 100, 191, 27));
        charBackGroundLine->setFont(font1);
        charBackGroundLine->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        charBackGroundLine->setFrame(false);
        charRaceLine = new QLineEdit(backGround1);
        charRaceLine->setObjectName(QString::fromUtf8("charRaceLine"));
        charRaceLine->setGeometry(QRect(560, 160, 231, 27));
        charRaceLine->setFont(font1);
        charRaceLine->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        charRaceLine->setFrame(false);
        charAlignmentLine = new QLineEdit(backGround1);
        charAlignmentLine->setObjectName(QString::fromUtf8("charAlignmentLine"));
        charAlignmentLine->setGeometry(QRect(800, 160, 191, 27));
        charAlignmentLine->setFont(font1);
        charAlignmentLine->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        charAlignmentLine->setFrame(false);
        expPointsLine = new QLineEdit(backGround1);
        expPointsLine->setObjectName(QString::fromUtf8("expPointsLine"));
        expPointsLine->setGeometry(QRect(1000, 160, 191, 27));
        expPointsLine->setFont(font1);
        expPointsLine->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        expPointsLine->setMaxLength(3);
        expPointsLine->setFrame(false);
        strengthSpinBox = new QSpinBox(backGround1);
        strengthSpinBox->setObjectName(QString::fromUtf8("strengthSpinBox"));
        strengthSpinBox->setGeometry(QRect(80, 330, 81, 51));
        strengthSpinBox->setFont(font);
        strengthSpinBox->setFocusPolicy(Qt::StrongFocus);
        strengthSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        strengthSpinBox->setFrame(false);
        strengthSpinBox->setAlignment(Qt::AlignCenter);
        strengthSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        strengthSpinBox->setMinimum(-99);
        dexteritySpinBox = new QSpinBox(backGround1);
        dexteritySpinBox->setObjectName(QString::fromUtf8("dexteritySpinBox"));
        dexteritySpinBox->setGeometry(QRect(80, 480, 81, 51));
        dexteritySpinBox->setFont(font);
        dexteritySpinBox->setFocusPolicy(Qt::StrongFocus);
        dexteritySpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        dexteritySpinBox->setFrame(false);
        dexteritySpinBox->setAlignment(Qt::AlignCenter);
        dexteritySpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        dexteritySpinBox->setMinimum(-99);
        constitutionSpinBox = new QSpinBox(backGround1);
        constitutionSpinBox->setObjectName(QString::fromUtf8("constitutionSpinBox"));
        constitutionSpinBox->setGeometry(QRect(80, 630, 81, 51));
        constitutionSpinBox->setFont(font);
        constitutionSpinBox->setFocusPolicy(Qt::StrongFocus);
        constitutionSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        constitutionSpinBox->setFrame(false);
        constitutionSpinBox->setAlignment(Qt::AlignCenter);
        constitutionSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        constitutionSpinBox->setMinimum(-99);
        intelligenceSpinBox = new QSpinBox(backGround1);
        intelligenceSpinBox->setObjectName(QString::fromUtf8("intelligenceSpinBox"));
        intelligenceSpinBox->setGeometry(QRect(80, 780, 81, 51));
        intelligenceSpinBox->setFont(font);
        intelligenceSpinBox->setFocusPolicy(Qt::StrongFocus);
        intelligenceSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        intelligenceSpinBox->setFrame(false);
        intelligenceSpinBox->setAlignment(Qt::AlignCenter);
        intelligenceSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        intelligenceSpinBox->setMinimum(-99);
        wisdomSpinBox = new QSpinBox(backGround1);
        wisdomSpinBox->setObjectName(QString::fromUtf8("wisdomSpinBox"));
        wisdomSpinBox->setGeometry(QRect(80, 930, 81, 51));
        wisdomSpinBox->setFont(font);
        wisdomSpinBox->setFocusPolicy(Qt::StrongFocus);
        wisdomSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        wisdomSpinBox->setFrame(false);
        wisdomSpinBox->setAlignment(Qt::AlignCenter);
        wisdomSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        wisdomSpinBox->setMinimum(-99);
        charismaSpinBox = new QSpinBox(backGround1);
        charismaSpinBox->setObjectName(QString::fromUtf8("charismaSpinBox"));
        charismaSpinBox->setGeometry(QRect(80, 1080, 81, 51));
        charismaSpinBox->setFont(font);
        charismaSpinBox->setFocusPolicy(Qt::StrongFocus);
        charismaSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        charismaSpinBox->setFrame(false);
        charismaSpinBox->setAlignment(Qt::AlignCenter);
        charismaSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        charismaSpinBox->setMinimum(-99);
        strengthLineEdit = new QLineEdit(backGround1);
        strengthLineEdit->setObjectName(QString::fromUtf8("strengthLineEdit"));
        strengthLineEdit->setGeometry(QRect(100, 390, 41, 25));
        QFont font2;
        font2.setFamily(QString::fromUtf8("URW Bookman L"));
        font2.setPointSize(12);
        strengthLineEdit->setFont(font2);
        strengthLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        strengthLineEdit->setMaxLength(2);
        strengthLineEdit->setFrame(false);
        strengthLineEdit->setAlignment(Qt::AlignCenter);
        dexterityLineEdit = new QLineEdit(backGround1);
        dexterityLineEdit->setObjectName(QString::fromUtf8("dexterityLineEdit"));
        dexterityLineEdit->setGeometry(QRect(100, 540, 41, 25));
        dexterityLineEdit->setFont(font2);
        dexterityLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        dexterityLineEdit->setMaxLength(2);
        dexterityLineEdit->setFrame(false);
        dexterityLineEdit->setAlignment(Qt::AlignCenter);
        constitutionLineEdit = new QLineEdit(backGround1);
        constitutionLineEdit->setObjectName(QString::fromUtf8("constitutionLineEdit"));
        constitutionLineEdit->setGeometry(QRect(100, 690, 41, 25));
        constitutionLineEdit->setFont(font2);
        constitutionLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        constitutionLineEdit->setMaxLength(2);
        constitutionLineEdit->setFrame(false);
        constitutionLineEdit->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        intelligenceLineEdit = new QLineEdit(backGround1);
        intelligenceLineEdit->setObjectName(QString::fromUtf8("intelligenceLineEdit"));
        intelligenceLineEdit->setGeometry(QRect(100, 840, 41, 25));
        intelligenceLineEdit->setFont(font2);
        intelligenceLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        intelligenceLineEdit->setMaxLength(2);
        intelligenceLineEdit->setFrame(false);
        intelligenceLineEdit->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        wisdomLineEdit = new QLineEdit(backGround1);
        wisdomLineEdit->setObjectName(QString::fromUtf8("wisdomLineEdit"));
        wisdomLineEdit->setGeometry(QRect(100, 990, 41, 25));
        wisdomLineEdit->setFont(font2);
        wisdomLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        wisdomLineEdit->setMaxLength(2);
        wisdomLineEdit->setFrame(false);
        wisdomLineEdit->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        charismaLineEdit = new QLineEdit(backGround1);
        charismaLineEdit->setObjectName(QString::fromUtf8("charismaLineEdit"));
        charismaLineEdit->setGeometry(QRect(100, 1140, 41, 25));
        charismaLineEdit->setFont(font2);
        charismaLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        charismaLineEdit->setMaxLength(2);
        charismaLineEdit->setFrame(false);
        charismaLineEdit->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        passiveWisdomLineEdit = new QLineEdit(backGround1);
        passiveWisdomLineEdit->setObjectName(QString::fromUtf8("passiveWisdomLineEdit"));
        passiveWisdomLineEdit->setGeometry(QRect(70, 1230, 41, 41));
        passiveWisdomLineEdit->setFont(font1);
        passiveWisdomLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        passiveWisdomLineEdit->setMaxLength(2);
        passiveWisdomLineEdit->setFrame(false);
        passiveWisdomLineEdit->setAlignment(Qt::AlignCenter);
        playerNameLine = new QLineEdit(backGround1);
        playerNameLine->setObjectName(QString::fromUtf8("playerNameLine"));
        playerNameLine->setGeometry(QRect(1000, 100, 191, 27));
        playerNameLine->setFont(font1);
        playerNameLine->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        playerNameLine->setFrame(false);
        attackAndSpellEdit = new QPlainTextEdit(backGround1);
        attackAndSpellEdit->setObjectName(QString::fromUtf8("attackAndSpellEdit"));
        attackAndSpellEdit->setGeometry(QRect(460, 940, 361, 241));
        attackAndSpellEdit->setFont(font1);
        attackAndSpellEdit->setStyleSheet(QString::fromUtf8("QPlainTextEdit{ background: rgba(0, 0, 0, 0); }"));
        profLangEdit = new QPlainTextEdit(backGround1);
        profLangEdit->setObjectName(QString::fromUtf8("profLangEdit"));
        profLangEdit->setGeometry(QRect(70, 1310, 351, 261));
        profLangEdit->setFont(font1);
        profLangEdit->setStyleSheet(QString::fromUtf8("QPlainTextEdit{ background: rgba(0, 0, 0, 0); }"));
        equipmentEdit = new QPlainTextEdit(backGround1);
        equipmentEdit->setObjectName(QString::fromUtf8("equipmentEdit"));
        equipmentEdit->setGeometry(QRect(560, 1240, 251, 331));
        equipmentEdit->setFont(font1);
        equipmentEdit->setStyleSheet(QString::fromUtf8("QPlainTextEdit{ background: rgba(0, 0, 0, 0); }"));
        personalityTraitsEdit = new QPlainTextEdit(backGround1);
        personalityTraitsEdit->setObjectName(QString::fromUtf8("personalityTraitsEdit"));
        personalityTraitsEdit->setGeometry(QRect(870, 290, 321, 101));
        QFont font3;
        font3.setFamily(QString::fromUtf8("URW Bookman L"));
        font3.setPointSize(13);
        personalityTraitsEdit->setFont(font3);
        personalityTraitsEdit->setStyleSheet(QString::fromUtf8("QPlainTextEdit{ background: rgba(0, 0, 0, 0); }"));
        idealsEdit = new QPlainTextEdit(backGround1);
        idealsEdit->setObjectName(QString::fromUtf8("idealsEdit"));
        idealsEdit->setGeometry(QRect(870, 430, 321, 81));
        idealsEdit->setFont(font3);
        idealsEdit->setStyleSheet(QString::fromUtf8("QPlainTextEdit{ background: rgba(0, 0, 0, 0); }"));
        bondsEdit = new QPlainTextEdit(backGround1);
        bondsEdit->setObjectName(QString::fromUtf8("bondsEdit"));
        bondsEdit->setGeometry(QRect(870, 550, 321, 71));
        bondsEdit->setFont(font3);
        bondsEdit->setStyleSheet(QString::fromUtf8("QPlainTextEdit{ background: rgba(0, 0, 0, 0); }"));
        flawsEdit = new QPlainTextEdit(backGround1);
        flawsEdit->setObjectName(QString::fromUtf8("flawsEdit"));
        flawsEdit->setGeometry(QRect(870, 660, 321, 81));
        flawsEdit->setFont(font3);
        flawsEdit->setStyleSheet(QString::fromUtf8("QPlainTextEdit{ background: rgba(0, 0, 0, 0); }"));
        featuresTraitsEdit = new QPlainTextEdit(backGround1);
        featuresTraitsEdit->setObjectName(QString::fromUtf8("featuresTraitsEdit"));
        featuresTraitsEdit->setGeometry(QRect(850, 800, 361, 781));
        featuresTraitsEdit->setFont(font1);
        featuresTraitsEdit->setStyleSheet(QString::fromUtf8("QPlainTextEdit{ background: rgba(0, 0, 0, 0); }"));
        armorClassSpinBox = new QSpinBox(backGround1);
        armorClassSpinBox->setObjectName(QString::fromUtf8("armorClassSpinBox"));
        armorClassSpinBox->setGeometry(QRect(490, 300, 61, 51));
        armorClassSpinBox->setFont(font);
        armorClassSpinBox->setFocusPolicy(Qt::StrongFocus);
        armorClassSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        armorClassSpinBox->setFrame(false);
        armorClassSpinBox->setAlignment(Qt::AlignCenter);
        armorClassSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        armorClassSpinBox->setMinimum(0);
        initiativeSpinBox = new QSpinBox(backGround1);
        initiativeSpinBox->setObjectName(QString::fromUtf8("initiativeSpinBox"));
        initiativeSpinBox->setGeometry(QRect(610, 300, 61, 61));
        initiativeSpinBox->setFont(font);
        initiativeSpinBox->setFocusPolicy(Qt::StrongFocus);
        initiativeSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        initiativeSpinBox->setFrame(false);
        initiativeSpinBox->setAlignment(Qt::AlignCenter);
        initiativeSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        initiativeSpinBox->setMinimum(-99);
        speedSpinBox = new QSpinBox(backGround1);
        speedSpinBox->setObjectName(QString::fromUtf8("speedSpinBox"));
        speedSpinBox->setGeometry(QRect(720, 300, 81, 61));
        QFont font4;
        font4.setFamily(QString::fromUtf8("URW Bookman L"));
        font4.setPointSize(17);
        speedSpinBox->setFont(font4);
        speedSpinBox->setFocusPolicy(Qt::StrongFocus);
        speedSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        speedSpinBox->setFrame(false);
        speedSpinBox->setAlignment(Qt::AlignCenter);
        speedSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        speedSpinBox->setMinimum(0);
        hitPointsCurrentSpinBox = new QSpinBox(backGround1);
        hitPointsCurrentSpinBox->setObjectName(QString::fromUtf8("hitPointsCurrentSpinBox"));
        hitPointsCurrentSpinBox->setGeometry(QRect(480, 450, 321, 51));
        hitPointsCurrentSpinBox->setFont(font);
        hitPointsCurrentSpinBox->setFocusPolicy(Qt::StrongFocus);
        hitPointsCurrentSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        hitPointsCurrentSpinBox->setFrame(false);
        hitPointsCurrentSpinBox->setAlignment(Qt::AlignCenter);
        hitPointsCurrentSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        hitPointsCurrentSpinBox->setMinimum(0);
        hitPointsCurrentSpinBox->setMaximum(99);
        hitPointsTemporarySpinBox = new QSpinBox(backGround1);
        hitPointsTemporarySpinBox->setObjectName(QString::fromUtf8("hitPointsTemporarySpinBox"));
        hitPointsTemporarySpinBox->setGeometry(QRect(480, 560, 321, 51));
        hitPointsTemporarySpinBox->setFont(font);
        hitPointsTemporarySpinBox->setFocusPolicy(Qt::StrongFocus);
        hitPointsTemporarySpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        hitPointsTemporarySpinBox->setFrame(false);
        hitPointsTemporarySpinBox->setAlignment(Qt::AlignCenter);
        hitPointsTemporarySpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        hitPointsTemporarySpinBox->setMinimum(0);
        hitPointsTemporarySpinBox->setMaximum(99);
        hitDiceSpinBox = new QSpinBox(backGround1);
        hitDiceSpinBox->setObjectName(QString::fromUtf8("hitDiceSpinBox"));
        hitDiceSpinBox->setGeometry(QRect(480, 690, 141, 41));
        hitDiceSpinBox->setFont(font);
        hitDiceSpinBox->setFocusPolicy(Qt::StrongFocus);
        hitDiceSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        hitDiceSpinBox->setFrame(false);
        hitDiceSpinBox->setAlignment(Qt::AlignCenter);
        hitDiceSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        hitDiceSpinBox->setMinimum(0);
        hitDiceSpinBox->setMaximum(99);
        coinsCopperSpinBox = new QSpinBox(backGround1);
        coinsCopperSpinBox->setObjectName(QString::fromUtf8("coinsCopperSpinBox"));
        coinsCopperSpinBox->setGeometry(QRect(480, 1250, 61, 31));
        coinsCopperSpinBox->setFont(font1);
        coinsCopperSpinBox->setFocusPolicy(Qt::StrongFocus);
        coinsCopperSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        coinsCopperSpinBox->setFrame(false);
        coinsCopperSpinBox->setAlignment(Qt::AlignCenter);
        coinsCopperSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        coinsCopperSpinBox->setMinimum(0);
        coinsCopperSpinBox->setMaximum(999);
        coinsSilverSpinBox = new QSpinBox(backGround1);
        coinsSilverSpinBox->setObjectName(QString::fromUtf8("coinsSilverSpinBox"));
        coinsSilverSpinBox->setGeometry(QRect(480, 1300, 61, 41));
        coinsSilverSpinBox->setFont(font1);
        coinsSilverSpinBox->setFocusPolicy(Qt::StrongFocus);
        coinsSilverSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        coinsSilverSpinBox->setFrame(false);
        coinsSilverSpinBox->setAlignment(Qt::AlignCenter);
        coinsSilverSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        coinsSilverSpinBox->setMinimum(0);
        coinsSilverSpinBox->setMaximum(999);
        coinsElectrumSpinBox = new QSpinBox(backGround1);
        coinsElectrumSpinBox->setObjectName(QString::fromUtf8("coinsElectrumSpinBox"));
        coinsElectrumSpinBox->setGeometry(QRect(480, 1360, 61, 31));
        coinsElectrumSpinBox->setFont(font1);
        coinsElectrumSpinBox->setFocusPolicy(Qt::StrongFocus);
        coinsElectrumSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        coinsElectrumSpinBox->setFrame(false);
        coinsElectrumSpinBox->setAlignment(Qt::AlignCenter);
        coinsElectrumSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        coinsElectrumSpinBox->setMinimum(0);
        coinsElectrumSpinBox->setMaximum(999);
        coinsGoldSpinBox = new QSpinBox(backGround1);
        coinsGoldSpinBox->setObjectName(QString::fromUtf8("coinsGoldSpinBox"));
        coinsGoldSpinBox->setGeometry(QRect(480, 1410, 61, 31));
        coinsGoldSpinBox->setFont(font1);
        coinsGoldSpinBox->setFocusPolicy(Qt::StrongFocus);
        coinsGoldSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        coinsGoldSpinBox->setFrame(false);
        coinsGoldSpinBox->setAlignment(Qt::AlignCenter);
        coinsGoldSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        coinsGoldSpinBox->setMinimum(0);
        coinsGoldSpinBox->setMaximum(999);
        coinsPlatinumSpinBox = new QSpinBox(backGround1);
        coinsPlatinumSpinBox->setObjectName(QString::fromUtf8("coinsPlatinumSpinBox"));
        coinsPlatinumSpinBox->setGeometry(QRect(480, 1460, 61, 41));
        coinsPlatinumSpinBox->setFont(font1);
        coinsPlatinumSpinBox->setFocusPolicy(Qt::StrongFocus);
        coinsPlatinumSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        coinsPlatinumSpinBox->setFrame(false);
        coinsPlatinumSpinBox->setAlignment(Qt::AlignCenter);
        coinsPlatinumSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        coinsPlatinumSpinBox->setMinimum(0);
        coinsPlatinumSpinBox->setMaximum(999);
        savingThrowStrengthSpinBox = new QSpinBox(backGround1);
        savingThrowStrengthSpinBox->setObjectName(QString::fromUtf8("savingThrowStrengthSpinBox"));
        savingThrowStrengthSpinBox->setGeometry(QRect(230, 430, 41, 21));
        QFont font5;
        font5.setFamily(QString::fromUtf8("URW Bookman L"));
        font5.setPointSize(10);
        savingThrowStrengthSpinBox->setFont(font5);
        savingThrowStrengthSpinBox->setFocusPolicy(Qt::StrongFocus);
        savingThrowStrengthSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        savingThrowStrengthSpinBox->setFrame(false);
        savingThrowStrengthSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        savingThrowStrengthSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        savingThrowStrengthSpinBox->setMinimum(-99);
        savingThrowDexteritySpinBox = new QSpinBox(backGround1);
        savingThrowDexteritySpinBox->setObjectName(QString::fromUtf8("savingThrowDexteritySpinBox"));
        savingThrowDexteritySpinBox->setGeometry(QRect(230, 450, 41, 31));
        savingThrowDexteritySpinBox->setFont(font5);
        savingThrowDexteritySpinBox->setFocusPolicy(Qt::StrongFocus);
        savingThrowDexteritySpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        savingThrowDexteritySpinBox->setFrame(false);
        savingThrowDexteritySpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        savingThrowDexteritySpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        savingThrowDexteritySpinBox->setMinimum(-99);
        savingThrowConstitutionSpinBox = new QSpinBox(backGround1);
        savingThrowConstitutionSpinBox->setObjectName(QString::fromUtf8("savingThrowConstitutionSpinBox"));
        savingThrowConstitutionSpinBox->setGeometry(QRect(230, 480, 41, 21));
        savingThrowConstitutionSpinBox->setFont(font5);
        savingThrowConstitutionSpinBox->setFocusPolicy(Qt::StrongFocus);
        savingThrowConstitutionSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        savingThrowConstitutionSpinBox->setFrame(false);
        savingThrowConstitutionSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        savingThrowConstitutionSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        savingThrowConstitutionSpinBox->setMinimum(-99);
        savingThrowIntelligenceSpinBox = new QSpinBox(backGround1);
        savingThrowIntelligenceSpinBox->setObjectName(QString::fromUtf8("savingThrowIntelligenceSpinBox"));
        savingThrowIntelligenceSpinBox->setGeometry(QRect(230, 510, 41, 21));
        savingThrowIntelligenceSpinBox->setFont(font5);
        savingThrowIntelligenceSpinBox->setFocusPolicy(Qt::StrongFocus);
        savingThrowIntelligenceSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        savingThrowIntelligenceSpinBox->setFrame(false);
        savingThrowIntelligenceSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        savingThrowIntelligenceSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        savingThrowIntelligenceSpinBox->setMinimum(-99);
        savingThrowWisdomSpinBox = new QSpinBox(backGround1);
        savingThrowWisdomSpinBox->setObjectName(QString::fromUtf8("savingThrowWisdomSpinBox"));
        savingThrowWisdomSpinBox->setGeometry(QRect(230, 540, 41, 21));
        savingThrowWisdomSpinBox->setFont(font5);
        savingThrowWisdomSpinBox->setFocusPolicy(Qt::StrongFocus);
        savingThrowWisdomSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        savingThrowWisdomSpinBox->setFrame(false);
        savingThrowWisdomSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        savingThrowWisdomSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        savingThrowWisdomSpinBox->setMinimum(-99);
        savingThrowCharismaSpinBox = new QSpinBox(backGround1);
        savingThrowCharismaSpinBox->setObjectName(QString::fromUtf8("savingThrowCharismaSpinBox"));
        savingThrowCharismaSpinBox->setGeometry(QRect(230, 570, 41, 21));
        savingThrowCharismaSpinBox->setFont(font5);
        savingThrowCharismaSpinBox->setFocusPolicy(Qt::StrongFocus);
        savingThrowCharismaSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        savingThrowCharismaSpinBox->setFrame(false);
        savingThrowCharismaSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        savingThrowCharismaSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        savingThrowCharismaSpinBox->setMinimum(-99);
        skillAcrobaticsSpinBox = new QSpinBox(backGround1);
        skillAcrobaticsSpinBox->setObjectName(QString::fromUtf8("skillAcrobaticsSpinBox"));
        skillAcrobaticsSpinBox->setGeometry(QRect(230, 660, 41, 31));
        skillAcrobaticsSpinBox->setFont(font5);
        skillAcrobaticsSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillAcrobaticsSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillAcrobaticsSpinBox->setFrame(false);
        skillAcrobaticsSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillAcrobaticsSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillAcrobaticsSpinBox->setMinimum(-99);
        skillAnimalHandlingSpinBox = new QSpinBox(backGround1);
        skillAnimalHandlingSpinBox->setObjectName(QString::fromUtf8("skillAnimalHandlingSpinBox"));
        skillAnimalHandlingSpinBox->setGeometry(QRect(230, 690, 41, 31));
        skillAnimalHandlingSpinBox->setFont(font5);
        skillAnimalHandlingSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillAnimalHandlingSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillAnimalHandlingSpinBox->setFrame(false);
        skillAnimalHandlingSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillAnimalHandlingSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillAnimalHandlingSpinBox->setMinimum(-99);
        skillArcanaSpinBox = new QSpinBox(backGround1);
        skillArcanaSpinBox->setObjectName(QString::fromUtf8("skillArcanaSpinBox"));
        skillArcanaSpinBox->setGeometry(QRect(230, 720, 41, 21));
        skillArcanaSpinBox->setFont(font5);
        skillArcanaSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillArcanaSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillArcanaSpinBox->setFrame(false);
        skillArcanaSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillArcanaSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillArcanaSpinBox->setMinimum(-99);
        skillAthleticsSpinBox = new QSpinBox(backGround1);
        skillAthleticsSpinBox->setObjectName(QString::fromUtf8("skillAthleticsSpinBox"));
        skillAthleticsSpinBox->setGeometry(QRect(230, 750, 41, 21));
        skillAthleticsSpinBox->setFont(font5);
        skillAthleticsSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillAthleticsSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillAthleticsSpinBox->setFrame(false);
        skillAthleticsSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillAthleticsSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillAthleticsSpinBox->setMinimum(-99);
        skillDeceptionSpinBox = new QSpinBox(backGround1);
        skillDeceptionSpinBox->setObjectName(QString::fromUtf8("skillDeceptionSpinBox"));
        skillDeceptionSpinBox->setGeometry(QRect(230, 780, 41, 21));
        skillDeceptionSpinBox->setFont(font5);
        skillDeceptionSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillDeceptionSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillDeceptionSpinBox->setFrame(false);
        skillDeceptionSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillDeceptionSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillDeceptionSpinBox->setMinimum(-99);
        skillHistorySpinBox = new QSpinBox(backGround1);
        skillHistorySpinBox->setObjectName(QString::fromUtf8("skillHistorySpinBox"));
        skillHistorySpinBox->setGeometry(QRect(230, 800, 41, 31));
        skillHistorySpinBox->setFont(font5);
        skillHistorySpinBox->setFocusPolicy(Qt::StrongFocus);
        skillHistorySpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillHistorySpinBox->setFrame(false);
        skillHistorySpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillHistorySpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillHistorySpinBox->setMinimum(-99);
        skillInsightSpinBox = new QSpinBox(backGround1);
        skillInsightSpinBox->setObjectName(QString::fromUtf8("skillInsightSpinBox"));
        skillInsightSpinBox->setGeometry(QRect(230, 830, 41, 31));
        skillInsightSpinBox->setFont(font5);
        skillInsightSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillInsightSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillInsightSpinBox->setFrame(false);
        skillInsightSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillInsightSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillInsightSpinBox->setMinimum(-99);
        skillIntimidationSpinBox = new QSpinBox(backGround1);
        skillIntimidationSpinBox->setObjectName(QString::fromUtf8("skillIntimidationSpinBox"));
        skillIntimidationSpinBox->setGeometry(QRect(230, 860, 41, 21));
        skillIntimidationSpinBox->setFont(font5);
        skillIntimidationSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillIntimidationSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillIntimidationSpinBox->setFrame(false);
        skillIntimidationSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillIntimidationSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillIntimidationSpinBox->setMinimum(-99);
        skillInvestigationSpinBox = new QSpinBox(backGround1);
        skillInvestigationSpinBox->setObjectName(QString::fromUtf8("skillInvestigationSpinBox"));
        skillInvestigationSpinBox->setGeometry(QRect(230, 890, 41, 21));
        skillInvestigationSpinBox->setFont(font5);
        skillInvestigationSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillInvestigationSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillInvestigationSpinBox->setFrame(false);
        skillInvestigationSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillInvestigationSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillInvestigationSpinBox->setMinimum(-99);
        skillMedicineSpinBox = new QSpinBox(backGround1);
        skillMedicineSpinBox->setObjectName(QString::fromUtf8("skillMedicineSpinBox"));
        skillMedicineSpinBox->setGeometry(QRect(230, 920, 41, 21));
        skillMedicineSpinBox->setFont(font5);
        skillMedicineSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillMedicineSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillMedicineSpinBox->setFrame(false);
        skillMedicineSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillMedicineSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillMedicineSpinBox->setMinimum(-99);
        skillNatureSpinBox = new QSpinBox(backGround1);
        skillNatureSpinBox->setObjectName(QString::fromUtf8("skillNatureSpinBox"));
        skillNatureSpinBox->setGeometry(QRect(230, 950, 41, 21));
        skillNatureSpinBox->setFont(font5);
        skillNatureSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillNatureSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillNatureSpinBox->setFrame(false);
        skillNatureSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillNatureSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillNatureSpinBox->setMinimum(-99);
        skillPerceptionSpinBox = new QSpinBox(backGround1);
        skillPerceptionSpinBox->setObjectName(QString::fromUtf8("skillPerceptionSpinBox"));
        skillPerceptionSpinBox->setGeometry(QRect(230, 970, 41, 31));
        skillPerceptionSpinBox->setFont(font5);
        skillPerceptionSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillPerceptionSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillPerceptionSpinBox->setFrame(false);
        skillPerceptionSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillPerceptionSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillPerceptionSpinBox->setMinimum(-99);
        skillPerformanceSpinBox = new QSpinBox(backGround1);
        skillPerformanceSpinBox->setObjectName(QString::fromUtf8("skillPerformanceSpinBox"));
        skillPerformanceSpinBox->setGeometry(QRect(230, 1000, 41, 31));
        skillPerformanceSpinBox->setFont(font5);
        skillPerformanceSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillPerformanceSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillPerformanceSpinBox->setFrame(false);
        skillPerformanceSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillPerformanceSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillPerformanceSpinBox->setMinimum(-99);
        skillPersuasionSpinBox = new QSpinBox(backGround1);
        skillPersuasionSpinBox->setObjectName(QString::fromUtf8("skillPersuasionSpinBox"));
        skillPersuasionSpinBox->setGeometry(QRect(230, 1030, 41, 21));
        skillPersuasionSpinBox->setFont(font5);
        skillPersuasionSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillPersuasionSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillPersuasionSpinBox->setFrame(false);
        skillPersuasionSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillPersuasionSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillPersuasionSpinBox->setMinimum(-99);
        skillReligionSpinBox = new QSpinBox(backGround1);
        skillReligionSpinBox->setObjectName(QString::fromUtf8("skillReligionSpinBox"));
        skillReligionSpinBox->setGeometry(QRect(230, 1060, 41, 21));
        skillReligionSpinBox->setFont(font5);
        skillReligionSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillReligionSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillReligionSpinBox->setFrame(false);
        skillReligionSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillReligionSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillReligionSpinBox->setMinimum(-99);
        skillSleightOfHandSpinBox = new QSpinBox(backGround1);
        skillSleightOfHandSpinBox->setObjectName(QString::fromUtf8("skillSleightOfHandSpinBox"));
        skillSleightOfHandSpinBox->setGeometry(QRect(230, 1090, 41, 21));
        skillSleightOfHandSpinBox->setFont(font5);
        skillSleightOfHandSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillSleightOfHandSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillSleightOfHandSpinBox->setFrame(false);
        skillSleightOfHandSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillSleightOfHandSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillSleightOfHandSpinBox->setMinimum(-99);
        skillStealthSpinBox = new QSpinBox(backGround1);
        skillStealthSpinBox->setObjectName(QString::fromUtf8("skillStealthSpinBox"));
        skillStealthSpinBox->setGeometry(QRect(230, 1110, 41, 31));
        skillStealthSpinBox->setFont(font5);
        skillStealthSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillStealthSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillStealthSpinBox->setFrame(false);
        skillStealthSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillStealthSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillStealthSpinBox->setMinimum(-99);
        skillSurvivalSpinBox = new QSpinBox(backGround1);
        skillSurvivalSpinBox->setObjectName(QString::fromUtf8("skillSurvivalSpinBox"));
        skillSurvivalSpinBox->setGeometry(QRect(230, 1140, 41, 31));
        skillSurvivalSpinBox->setFont(font5);
        skillSurvivalSpinBox->setFocusPolicy(Qt::StrongFocus);
        skillSurvivalSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        skillSurvivalSpinBox->setFrame(false);
        skillSurvivalSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        skillSurvivalSpinBox->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        skillSurvivalSpinBox->setMinimum(-99);
        inspirationLineEdit = new QLineEdit(backGround1);
        inspirationLineEdit->setObjectName(QString::fromUtf8("inspirationLineEdit"));
        inspirationLineEdit->setGeometry(QRect(200, 270, 51, 41));
        inspirationLineEdit->setFont(font1);
        inspirationLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        inspirationLineEdit->setMaxLength(2);
        inspirationLineEdit->setFrame(false);
        inspirationLineEdit->setAlignment(Qt::AlignCenter);
        profBonusSpinBox = new QSpinBox(backGround1);
        profBonusSpinBox->setObjectName(QString::fromUtf8("profBonusSpinBox"));
        profBonusSpinBox->setGeometry(QRect(200, 350, 51, 41));
        profBonusSpinBox->setFont(font1);
        profBonusSpinBox->setFocusPolicy(Qt::StrongFocus);
        profBonusSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        profBonusSpinBox->setFrame(false);
        profBonusSpinBox->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        profBonusSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        profBonusSpinBox->setMinimum(0);
        hitPointsMaxLineEdit = new QLineEdit(backGround1);
        hitPointsMaxLineEdit->setObjectName(QString::fromUtf8("hitPointsMaxLineEdit"));
        hitPointsMaxLineEdit->setGeometry(QRect(610, 410, 181, 21));
        hitPointsMaxLineEdit->setFont(font2);
        hitPointsMaxLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        hitPointsMaxLineEdit->setMaxLength(3);
        hitPointsMaxLineEdit->setFrame(false);
        hitDiceTotalLineEdit = new QLineEdit(backGround1);
        hitDiceTotalLineEdit->setObjectName(QString::fromUtf8("hitDiceTotalLineEdit"));
        hitDiceTotalLineEdit->setGeometry(QRect(520, 661, 91, 20));
        hitDiceTotalLineEdit->setFont(font2);
        hitDiceTotalLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        hitDiceTotalLineEdit->setFrame(false);
        hitDiceTotalLineEdit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        attack1NameLineEdit = new QLineEdit(backGround1);
        attack1NameLineEdit->setObjectName(QString::fromUtf8("attack1NameLineEdit"));
        attack1NameLineEdit->setGeometry(QRect(470, 820, 121, 31));
        attack1NameLineEdit->setFont(font2);
        attack1NameLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        attack1NameLineEdit->setFrame(false);
        attack1NameLineEdit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        attack2NameLineEdit = new QLineEdit(backGround1);
        attack2NameLineEdit->setObjectName(QString::fromUtf8("attack2NameLineEdit"));
        attack2NameLineEdit->setGeometry(QRect(470, 860, 121, 31));
        attack2NameLineEdit->setFont(font2);
        attack2NameLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        attack2NameLineEdit->setFrame(false);
        attack2NameLineEdit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        attack3NameLineEdit = new QLineEdit(backGround1);
        attack3NameLineEdit->setObjectName(QString::fromUtf8("attack3NameLineEdit"));
        attack3NameLineEdit->setGeometry(QRect(470, 900, 121, 31));
        attack3NameLineEdit->setFont(font2);
        attack3NameLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        attack3NameLineEdit->setFrame(false);
        attack3NameLineEdit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        attack1DamageTypeLineEdit = new QLineEdit(backGround1);
        attack1DamageTypeLineEdit->setObjectName(QString::fromUtf8("attack1DamageTypeLineEdit"));
        attack1DamageTypeLineEdit->setGeometry(QRect(690, 820, 121, 31));
        attack1DamageTypeLineEdit->setFont(font2);
        attack1DamageTypeLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        attack1DamageTypeLineEdit->setFrame(false);
        attack1DamageTypeLineEdit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        attack2DamageTypeLineEdit = new QLineEdit(backGround1);
        attack2DamageTypeLineEdit->setObjectName(QString::fromUtf8("attack2DamageTypeLineEdit"));
        attack2DamageTypeLineEdit->setGeometry(QRect(690, 860, 121, 31));
        attack2DamageTypeLineEdit->setFont(font2);
        attack2DamageTypeLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        attack2DamageTypeLineEdit->setFrame(false);
        attack2DamageTypeLineEdit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        attack3DamageTypeLineEdit = new QLineEdit(backGround1);
        attack3DamageTypeLineEdit->setObjectName(QString::fromUtf8("attack3DamageTypeLineEdit"));
        attack3DamageTypeLineEdit->setGeometry(QRect(690, 900, 121, 31));
        attack3DamageTypeLineEdit->setFont(font2);
        attack3DamageTypeLineEdit->setStyleSheet(QString::fromUtf8("QLineEdit { background: rgba(0, 0, 0, 0); }"));
        attack3DamageTypeLineEdit->setFrame(false);
        attack3DamageTypeLineEdit->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        attack1BonusSpinBox = new QSpinBox(backGround1);
        attack1BonusSpinBox->setObjectName(QString::fromUtf8("attack1BonusSpinBox"));
        attack1BonusSpinBox->setGeometry(QRect(610, 820, 61, 31));
        attack1BonusSpinBox->setFont(font1);
        attack1BonusSpinBox->setFocusPolicy(Qt::StrongFocus);
        attack1BonusSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        attack1BonusSpinBox->setFrame(false);
        attack1BonusSpinBox->setAlignment(Qt::AlignCenter);
        attack1BonusSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        attack1BonusSpinBox->setMinimum(0);
        attack2BonusSpinBox = new QSpinBox(backGround1);
        attack2BonusSpinBox->setObjectName(QString::fromUtf8("attack2BonusSpinBox"));
        attack2BonusSpinBox->setGeometry(QRect(610, 860, 61, 31));
        attack2BonusSpinBox->setFont(font1);
        attack2BonusSpinBox->setFocusPolicy(Qt::StrongFocus);
        attack2BonusSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        attack2BonusSpinBox->setFrame(false);
        attack2BonusSpinBox->setAlignment(Qt::AlignCenter);
        attack2BonusSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        attack2BonusSpinBox->setMinimum(0);
        attack3BonusSpinBox = new QSpinBox(backGround1);
        attack3BonusSpinBox->setObjectName(QString::fromUtf8("attack3BonusSpinBox"));
        attack3BonusSpinBox->setGeometry(QRect(610, 900, 61, 31));
        attack3BonusSpinBox->setFont(font1);
        attack3BonusSpinBox->setFocusPolicy(Qt::StrongFocus);
        attack3BonusSpinBox->setStyleSheet(QString::fromUtf8("QSpinBox { background: rgba(0, 0, 0, 0); }"));
        attack3BonusSpinBox->setFrame(false);
        attack3BonusSpinBox->setAlignment(Qt::AlignCenter);
        attack3BonusSpinBox->setButtonSymbols(QAbstractSpinBox::UpDownArrows);
        attack3BonusSpinBox->setMinimum(0);
        savingThrowStrengthRadioButton = new QRadioButton(backGround1);
        savingThrowStrengthRadioButton->setObjectName(QString::fromUtf8("savingThrowStrengthRadioButton"));
        savingThrowStrengthRadioButton->setGeometry(QRect(210, 430, 16, 21));
        savingThrowStrengthRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        savingThrowStrengthRadioButton->setAutoExclusive(false);
        savingThrowDexterityRadioButton = new QRadioButton(backGround1);
        savingThrowDexterityRadioButton->setObjectName(QString::fromUtf8("savingThrowDexterityRadioButton"));
        savingThrowDexterityRadioButton->setGeometry(QRect(210, 450, 20, 31));
        savingThrowDexterityRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        savingThrowDexterityRadioButton->setAutoExclusive(false);
        savingThrowConstitutionRadioButton = new QRadioButton(backGround1);
        savingThrowConstitutionRadioButton->setObjectName(QString::fromUtf8("savingThrowConstitutionRadioButton"));
        savingThrowConstitutionRadioButton->setGeometry(QRect(210, 480, 16, 31));
        savingThrowConstitutionRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        savingThrowConstitutionRadioButton->setAutoExclusive(false);
        savingThrowIntelligenceRadioButton = new QRadioButton(backGround1);
        savingThrowIntelligenceRadioButton->setObjectName(QString::fromUtf8("savingThrowIntelligenceRadioButton"));
        savingThrowIntelligenceRadioButton->setGeometry(QRect(210, 510, 20, 31));
        savingThrowIntelligenceRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        savingThrowIntelligenceRadioButton->setAutoExclusive(false);
        savingThrowWisdomRadioButton = new QRadioButton(backGround1);
        savingThrowWisdomRadioButton->setObjectName(QString::fromUtf8("savingThrowWisdomRadioButton"));
        savingThrowWisdomRadioButton->setGeometry(QRect(210, 540, 16, 21));
        savingThrowWisdomRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        savingThrowWisdomRadioButton->setAutoExclusive(false);
        savingThrowCharismaRadioButton = new QRadioButton(backGround1);
        savingThrowCharismaRadioButton->setObjectName(QString::fromUtf8("savingThrowCharismaRadioButton"));
        savingThrowCharismaRadioButton->setGeometry(QRect(210, 570, 16, 21));
        savingThrowCharismaRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        savingThrowCharismaRadioButton->setAutoExclusive(false);
        skillAcrobaticsRadioButton = new QRadioButton(backGround1);
        skillAcrobaticsRadioButton->setObjectName(QString::fromUtf8("skillAcrobaticsRadioButton"));
        skillAcrobaticsRadioButton->setGeometry(QRect(210, 670, 16, 21));
        skillAcrobaticsRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillAcrobaticsRadioButton->setAutoExclusive(false);
        skillAnimalHandlingRadioButton = new QRadioButton(backGround1);
        skillAnimalHandlingRadioButton->setObjectName(QString::fromUtf8("skillAnimalHandlingRadioButton"));
        skillAnimalHandlingRadioButton->setGeometry(QRect(210, 700, 16, 21));
        skillAnimalHandlingRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillAnimalHandlingRadioButton->setAutoExclusive(false);
        skillArcanaRadioButton = new QRadioButton(backGround1);
        skillArcanaRadioButton->setObjectName(QString::fromUtf8("skillArcanaRadioButton"));
        skillArcanaRadioButton->setGeometry(QRect(210, 720, 16, 31));
        skillArcanaRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillArcanaRadioButton->setAutoExclusive(false);
        skillAthleticsRadioButton = new QRadioButton(backGround1);
        skillAthleticsRadioButton->setObjectName(QString::fromUtf8("skillAthleticsRadioButton"));
        skillAthleticsRadioButton->setGeometry(QRect(210, 750, 16, 21));
        skillAthleticsRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillAthleticsRadioButton->setAutoExclusive(false);
        skillDeceptionRadioButton = new QRadioButton(backGround1);
        skillDeceptionRadioButton->setObjectName(QString::fromUtf8("skillDeceptionRadioButton"));
        skillDeceptionRadioButton->setGeometry(QRect(210, 770, 16, 41));
        skillDeceptionRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillDeceptionRadioButton->setAutoExclusive(false);
        skillHistoryRadioButton = new QRadioButton(backGround1);
        skillHistoryRadioButton->setObjectName(QString::fromUtf8("skillHistoryRadioButton"));
        skillHistoryRadioButton->setGeometry(QRect(210, 800, 20, 31));
        skillHistoryRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillHistoryRadioButton->setAutoExclusive(false);
        skillInsightRadioButton = new QRadioButton(backGround1);
        skillInsightRadioButton->setObjectName(QString::fromUtf8("skillInsightRadioButton"));
        skillInsightRadioButton->setGeometry(QRect(210, 830, 20, 31));
        skillInsightRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillInsightRadioButton->setAutoExclusive(false);
        skillIntimidationRadioButton = new QRadioButton(backGround1);
        skillIntimidationRadioButton->setObjectName(QString::fromUtf8("skillIntimidationRadioButton"));
        skillIntimidationRadioButton->setGeometry(QRect(210, 860, 20, 31));
        skillIntimidationRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillIntimidationRadioButton->setAutoExclusive(false);
        skillInvestigationRadioButton = new QRadioButton(backGround1);
        skillInvestigationRadioButton->setObjectName(QString::fromUtf8("skillInvestigationRadioButton"));
        skillInvestigationRadioButton->setGeometry(QRect(210, 890, 16, 31));
        skillInvestigationRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillInvestigationRadioButton->setAutoExclusive(false);
        skillMedicineRadioButton = new QRadioButton(backGround1);
        skillMedicineRadioButton->setObjectName(QString::fromUtf8("skillMedicineRadioButton"));
        skillMedicineRadioButton->setGeometry(QRect(210, 920, 16, 21));
        skillMedicineRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillMedicineRadioButton->setAutoExclusive(false);
        skillNatureRadioButton = new QRadioButton(backGround1);
        skillNatureRadioButton->setObjectName(QString::fromUtf8("skillNatureRadioButton"));
        skillNatureRadioButton->setGeometry(QRect(210, 940, 20, 31));
        skillNatureRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillNatureRadioButton->setAutoExclusive(false);
        skillPerceptionRadioButton = new QRadioButton(backGround1);
        skillPerceptionRadioButton->setObjectName(QString::fromUtf8("skillPerceptionRadioButton"));
        skillPerceptionRadioButton->setGeometry(QRect(210, 970, 20, 31));
        skillPerceptionRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillPerceptionRadioButton->setAutoExclusive(false);
        skillPerformanceRadioButton = new QRadioButton(backGround1);
        skillPerformanceRadioButton->setObjectName(QString::fromUtf8("skillPerformanceRadioButton"));
        skillPerformanceRadioButton->setGeometry(QRect(210, 1000, 20, 31));
        skillPerformanceRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillPerformanceRadioButton->setAutoExclusive(false);
        skillPersuasionRadioButton = new QRadioButton(backGround1);
        skillPersuasionRadioButton->setObjectName(QString::fromUtf8("skillPersuasionRadioButton"));
        skillPersuasionRadioButton->setGeometry(QRect(210, 1030, 16, 31));
        skillPersuasionRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillPersuasionRadioButton->setAutoExclusive(false);
        skillReligionRadioButton = new QRadioButton(backGround1);
        skillReligionRadioButton->setObjectName(QString::fromUtf8("skillReligionRadioButton"));
        skillReligionRadioButton->setGeometry(QRect(210, 1060, 16, 21));
        skillReligionRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillReligionRadioButton->setAutoExclusive(false);
        skillSleightOfHandRadioButton = new QRadioButton(backGround1);
        skillSleightOfHandRadioButton->setObjectName(QString::fromUtf8("skillSleightOfHandRadioButton"));
        skillSleightOfHandRadioButton->setGeometry(QRect(210, 1090, 20, 21));
        skillSleightOfHandRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillSleightOfHandRadioButton->setAutoExclusive(false);
        skillStealthRadioButton = new QRadioButton(backGround1);
        skillStealthRadioButton->setObjectName(QString::fromUtf8("skillStealthRadioButton"));
        skillStealthRadioButton->setGeometry(QRect(210, 1110, 20, 31));
        skillStealthRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillStealthRadioButton->setAutoExclusive(false);
        skillSurvivalRadioButton = new QRadioButton(backGround1);
        skillSurvivalRadioButton->setObjectName(QString::fromUtf8("skillSurvivalRadioButton"));
        skillSurvivalRadioButton->setGeometry(QRect(210, 1140, 16, 31));
        skillSurvivalRadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        skillSurvivalRadioButton->setAutoExclusive(false);
        success1RadioButton = new QRadioButton(backGround1);
        success1RadioButton->setObjectName(QString::fromUtf8("success1RadioButton"));
        success1RadioButton->setGeometry(QRect(720, 670, 31, 21));
        success1RadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        success1RadioButton->setAutoExclusive(false);
        success2RadioButton = new QRadioButton(backGround1);
        success2RadioButton->setObjectName(QString::fromUtf8("success2RadioButton"));
        success2RadioButton->setGeometry(QRect(750, 670, 31, 21));
        success2RadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        success2RadioButton->setAutoExclusive(false);
        success3RadioButton = new QRadioButton(backGround1);
        success3RadioButton->setObjectName(QString::fromUtf8("success3RadioButton"));
        success3RadioButton->setGeometry(QRect(780, 670, 16, 21));
        success3RadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        success3RadioButton->setAutoExclusive(false);
        failur1RadioButton = new QRadioButton(backGround1);
        failur1RadioButton->setObjectName(QString::fromUtf8("failur1RadioButton"));
        failur1RadioButton->setGeometry(QRect(720, 700, 31, 31));
        failur1RadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        failur1RadioButton->setAutoExclusive(false);
        failur2RadioButton = new QRadioButton(backGround1);
        failur2RadioButton->setObjectName(QString::fromUtf8("failur2RadioButton"));
        failur2RadioButton->setGeometry(QRect(750, 700, 31, 31));
        failur2RadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        failur2RadioButton->setAutoExclusive(false);
        failur3RadioButton = new QRadioButton(backGround1);
        failur3RadioButton->setObjectName(QString::fromUtf8("failur3RadioButton"));
        failur3RadioButton->setGeometry(QRect(780, 700, 16, 31));
        failur3RadioButton->setStyleSheet(QString::fromUtf8("QRadioButton{ background: rgb(255, 255, 255); }\n"
""));
        failur3RadioButton->setAutoExclusive(false);

        gridLayout_4->addWidget(backGround1, 0, 0, 1, 1);

        scrollArea1->setWidget(scrollAreaWidgetContents1);

        gridLayout->addWidget(scrollArea1, 0, 0, 1, 1);

        stackedWidget->addWidget(page1);
        page2 = new QWidget();
        page2->setObjectName(QString::fromUtf8("page2"));
        gridLayout_2 = new QGridLayout(page2);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        scrollArea2 = new QScrollArea(page2);
        scrollArea2->setObjectName(QString::fromUtf8("scrollArea2"));
        scrollArea2->setWidgetResizable(false);
        scrollArea2->setAlignment(Qt::AlignCenter);
        scrollAreaWidgetContents2 = new QWidget();
        scrollAreaWidgetContents2->setObjectName(QString::fromUtf8("scrollAreaWidgetContents2"));
        scrollAreaWidgetContents2->setGeometry(QRect(0, 0, 1293, 1668));
        gridLayout_5 = new QGridLayout(scrollAreaWidgetContents2);
        gridLayout_5->setObjectName(QString::fromUtf8("gridLayout_5"));
        backGround2 = new QWidget(scrollAreaWidgetContents2);
        backGround2->setObjectName(QString::fromUtf8("backGround2"));
        backGround2->setMinimumSize(QSize(1275, 1650));
        backGround2->setMaximumSize(QSize(1275, 1650));
        backGround2->setStyleSheet(QString::fromUtf8("background-image: url(:/dndcs/2.png);"));

        gridLayout_5->addWidget(backGround2, 0, 0, 1, 1);

        scrollArea2->setWidget(scrollAreaWidgetContents2);

        gridLayout_2->addWidget(scrollArea2, 0, 0, 1, 1);

        stackedWidget->addWidget(page2);
        page3 = new QWidget();
        page3->setObjectName(QString::fromUtf8("page3"));
        gridLayout_3 = new QGridLayout(page3);
        gridLayout_3->setObjectName(QString::fromUtf8("gridLayout_3"));
        scrollArea3 = new QScrollArea(page3);
        scrollArea3->setObjectName(QString::fromUtf8("scrollArea3"));
        scrollArea3->setWidgetResizable(false);
        scrollArea3->setAlignment(Qt::AlignCenter);
        scrollAreaWidgetContents3 = new QWidget();
        scrollAreaWidgetContents3->setObjectName(QString::fromUtf8("scrollAreaWidgetContents3"));
        scrollAreaWidgetContents3->setGeometry(QRect(0, 0, 1293, 1668));
        gridLayout_6 = new QGridLayout(scrollAreaWidgetContents3);
        gridLayout_6->setObjectName(QString::fromUtf8("gridLayout_6"));
        backGround3 = new QWidget(scrollAreaWidgetContents3);
        backGround3->setObjectName(QString::fromUtf8("backGround3"));
        backGround3->setMinimumSize(QSize(1275, 1650));
        backGround3->setMaximumSize(QSize(1275, 1650));
        backGround3->setStyleSheet(QString::fromUtf8("background-image: url(:/dndcs/3.png);"));

        gridLayout_6->addWidget(backGround3, 0, 0, 1, 1);

        scrollArea3->setWidget(scrollAreaWidgetContents3);

        gridLayout_3->addWidget(scrollArea3, 0, 0, 1, 1);

        stackedWidget->addWidget(page3);

        verticalLayout->addWidget(stackedWidget);

        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer);

        buttonPrevPage = new QPushButton(CharacterSheet);
        buttonPrevPage->setObjectName(QString::fromUtf8("buttonPrevPage"));
        buttonPrevPage->setMinimumSize(QSize(150, 0));
        buttonPrevPage->setMaximumSize(QSize(150, 16777215));

        horizontalLayout->addWidget(buttonPrevPage);

        buttonNextPage = new QPushButton(CharacterSheet);
        buttonNextPage->setObjectName(QString::fromUtf8("buttonNextPage"));
        buttonNextPage->setMinimumSize(QSize(150, 0));
        buttonNextPage->setMaximumSize(QSize(150, 16777215));

        horizontalLayout->addWidget(buttonNextPage);

        horizontalSpacer_2 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_2);


        verticalLayout->addLayout(horizontalLayout);


        retranslateUi(CharacterSheet);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(CharacterSheet);
    } // setupUi

    void retranslateUi(QWidget *CharacterSheet)
    {
        CharacterSheet->setWindowTitle(QCoreApplication::translate("CharacterSheet", "Form", nullptr));
        charNameLine->setText(QString());
        passiveWisdomLineEdit->setPlaceholderText(QCoreApplication::translate("CharacterSheet", "0", nullptr));
        inspirationLineEdit->setPlaceholderText(QCoreApplication::translate("CharacterSheet", "0", nullptr));
        savingThrowStrengthRadioButton->setText(QString());
        savingThrowDexterityRadioButton->setText(QString());
        savingThrowConstitutionRadioButton->setText(QString());
        savingThrowIntelligenceRadioButton->setText(QString());
        savingThrowWisdomRadioButton->setText(QString());
        savingThrowCharismaRadioButton->setText(QString());
        skillAcrobaticsRadioButton->setText(QString());
        skillAnimalHandlingRadioButton->setText(QString());
        skillArcanaRadioButton->setText(QString());
        skillAthleticsRadioButton->setText(QString());
        skillDeceptionRadioButton->setText(QString());
        skillHistoryRadioButton->setText(QString());
        skillInsightRadioButton->setText(QString());
        skillIntimidationRadioButton->setText(QString());
        skillInvestigationRadioButton->setText(QString());
        skillMedicineRadioButton->setText(QString());
        skillNatureRadioButton->setText(QString());
        skillPerceptionRadioButton->setText(QString());
        skillPerformanceRadioButton->setText(QString());
        skillPersuasionRadioButton->setText(QString());
        skillReligionRadioButton->setText(QString());
        skillSleightOfHandRadioButton->setText(QString());
        skillStealthRadioButton->setText(QString());
        skillSurvivalRadioButton->setText(QString());
        success1RadioButton->setText(QString());
        success3RadioButton->setText(QString());
        failur1RadioButton->setText(QString());
        failur3RadioButton->setText(QString());
        buttonPrevPage->setText(QCoreApplication::translate("CharacterSheet", "<< Previous page", nullptr));
        buttonNextPage->setText(QCoreApplication::translate("CharacterSheet", "Next page >>", nullptr));
    } // retranslateUi

};

namespace Ui {
    class CharacterSheet: public Ui_CharacterSheet {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CHARACTERSHEET_H
